# Dart code analyze and pub dependencies check
name: Dart

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build web # run basic build test
#      - run: flutter test  # uncomment it if wrote unit test file