# Automatically build flutter web and upload to github pages
name: gh-pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.7.1
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          webRenderer: html
          customArgs: --dart-define=FLUTTER_WEB_CANVASKIT_URL=https://cdn.jsdelivr.net/npm/canvaskit-wasm/bin/